# Generated by Django 6.0.3 on 2026-03-27 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expensemodel',
            name='amount',
            field=models.CharField(max_length=200),
        ),
    ]
